---
# tasks file for ansible-role-python
- import_tasks: install.deb.yml
  when: ansible_os_family == 'Debian'

- import_tasks: install.yum.yml
  when: ansible_os_family == 'RedHat'

- name: install python-pip
  package:
    name: python-pip
    state: present

- name: Install global python packages
  pip: 
    name: "{{item}}"
  with_items:
    - "{{ python_install }}"

- name: Workaround - Remove python-openssl
  apt:
    name: python-openssl
    state: absent
  when: (ubuntu_python_openssl_workaround and ansible_os_family == 'Debian')

- name: Workaround - Install pyOpenSSL with pip
  pip:
    name: pyOpenSSL
  when: (ubuntu_python_openssl_workaround and ansible_os_family == 'Debian')
